# Generated by Django 5.1.3 on 2024-11-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('articletext', models.TextField(verbose_name='Текст Статті')),
                ('date', models.DateField(verbose_name='Дата публікації')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ім`я')),
                ('email', models.EmailField(max_length=254, verbose_name='example@gmail.com')),
                ('commenttext', models.TextField(max_length=200, verbose_name='Текст коментаря')),
                ('date', models.DateField(verbose_name='Дата публікації')),
                ('articlekey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.articles')),
            ],
        ),
    ]
