# Generated by Django 5.1.3 on 2024-11-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Кількість лайків'),
        ),
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Кількість переглядів'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публікації'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публікації'),
        ),
    ]
