# Generated by Django 5.1.3 on 2024-11-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articles_likes_articles_views_alter_articles_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Коментар', 'verbose_name_plural': 'Коментарі'},
        ),
    ]
