# Generated by Django 5.1.3 on 2024-11-22 17:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_options_alter_comments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='articletype',
            field=models.CharField(choices=[('новина', 'новина'), ('підбірка', 'підбірка'), ('стаття', 'стаття')], default='стаття', max_length=20),
        ),
        migrations.AlterField(
            model_name='articles',
            name='articletext',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст Статті'),
        ),
    ]
