# Generated by Django 5.1.3 on 2024-11-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articles_articletype_alter_articles_articletext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='views',
        ),
        migrations.AlterField(
            model_name='articles',
            name='articletype',
            field=models.CharField(choices=[('огляд', 'огляд'), ('підбірка', 'підбірка'), ('стаття', 'стаття')], default='стаття', max_length=20, verbose_name='Тип новини'),
        ),
    ]
