# Generated by Django 5.1.3 on 2024-11-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_comments_articlekey_articlereaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlereaction',
            options={'verbose_name': 'Взаємодія', 'verbose_name_plural': 'Взаємодії'},
        ),
    ]
