# Generated by Django 5.1.3 on 2024-11-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_articlereaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='previewimage',
            field=models.ImageField(default='static/img/placeholder.png', upload_to='uploads/', verbose_name='Превью'),
        ),
    ]
