# Generated by Django 5.1.3 on 2024-11-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_articles_previewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='previewimage',
            field=models.ImageField(default='news/static/img/placeholder.png', max_length=50, upload_to='uploads/', verbose_name='Превью'),
        ),
    ]
