# Generated by Django 5.1.3 on 2024-11-23 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_articles_previewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='articlekey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.articles'),
        ),
    ]
